version: '3'
services:
  web:
    image: fcogmes92/drinks-server
    build:
      context: ./

    ports:
      - '8000:80'
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
