version: '3'
services:
  web:
    image: fcogmes92/drinks-server
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PORT=3000
    ports:
      - '8000:3000'
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
